### PR TITLE
upgrade to Python 3.8

### PR DESCRIPTION
**Pull request by grahame**
- move the mongo and web containers into directories (greatly
  decreases build time)
- local_settings.py is now bind-mounted into web container, so rebuild
  is not required after modification
- web container uses Python 3.8
- install pyre2 into web container
- local_settings.py updated to latest template from Sefaria-Web

### CODE REVIEW

**Comment by grahame** [comment]
Current state of this PR – everything builds fine, but when I browse to localhost:8000 I get:

```
KeyError at / 'Daf Yomi'
```

I'm suspicious that something is wrong with Mongo, but it's hit midnight so I'm going to call it a night. Any chance someone could take a look? 😊

**Comment by grahame** [comment]
I think I've identified the problem: the import of the dump into the mongodb container is only partially successful. I am chasing it down now.

**Comment by yehosef** [comment]
Looking forward to giving this a spin!  Thanks @grahame

**Comment by nsantacruz** [comment]
@grahame this seems to be working fine. Sorry about the delay! This repo is not commonly used yet but hopefully more people will use it and point out issues with it.

**Pull request merged**
